#THIS MAKE FILE WAS GENERATED BY AI 

# Makefile for Lorenz Attractor 
# Works on Linux, OSX and Windows (MinGW)

# Executable name
EXE=Assignment-1

# Main target
all: $(EXE)

# Detect OS and set flags
ifeq "$(OS)" "Windows_NT"
CFLAGS=-Wall -DUSEGLEW
LIBS=-lfreeglut -lglew32 -lglu32 -lopengl32 -lm
else
UNAME=$(shell uname)
ifeq "$(UNAME)" "Darwin"
CFLAGS=-Wall -Wno-deprecated-declarations
LIBS=-framework GLUT -framework OpenGL
else
CFLAGS=-Wall
LIBS=-lglut -lGLU -lGL -lm
endif
endif

# Compile rule
$(EXE): assignment.c
	gcc $(CFLAGS) -o $(EXE) assignment.c $(LIBS)

# Remove generated files
clean:
	rm -f $(EXE) *.exe *.o